<?php

/**
 * @file
 * Display Suite Basic Layout configuration.
 */

function ds_basic_layout() {
  return array(
    'label' => t('Basic Layout'),
    'regions' => array(
      'section1' => t('Section1'),
      'section2' => t('Section2'),
      'section3' => t('Section3'),
      'section4' => t('Section4'),
      'section5' => t('Section5'),
      'section6' => t('Section6'),
      'section7' => t('Section7'),
      'section8' => t('Section8'),
      'section9' => t('Section9'),
      'section10' => t('Section10'),
      'section11' => t('Section11'),
      'section12' => t('Section12'),
      'section13' => t('Reviews'),
    ),
    // Uncomment if you want to include a CSS file for this layout (basic_layout.css)
    // 'css' => TRUE,
    // Uncomment if you want to include a preview for this layout (basic_layout.png)
    // 'image' => TRUE,
  );
}
